### PR TITLE
Addressing selfie attacks

### PR DESCRIPTION
**Pull request by ms-s**
Text on addressing Selfie attack based on contributions by Tuomas Aura and Mohit Sethi.

### CODE REVIEW

**Comment by ms-s** [comment]
I understand the need to simplify the text. However, external PSKs are (and will continue to be) used in many different settings. Please have a look at "Continuing to reflect on TLS 1.3 with external PSK" by Akhmetzyanova et al. : https://eprint.iacr.org/2019/421 which discusses the various applications of external PSKs in IoT and group chats. 

The current text does not try to fix attacks originating from malicious insiders in a group (and I don't think that this draft is the right place to do that). However, the current text does fix selfie (and other re-routing attacks) with minimal requirements from implementations. 

If there is certain sections of the text that can be improved/simplified, I can certainly make changes. But simply saying that the roles need to be unique will not prevent implementations from doing otherwise. Besides, they are important enough use-cases that we should fix the attacks for them here.

**Comment by chris-wood** [comment]
@ms-s I don’t follow. As you say, no amount of text will prevent implementations from doing the wrong thing. All we can do is offer guidance, and our guidance is that identifiers be unique. Your proposed text does not add anything new beyond this point. Thus, I propose replacing this PR with a much smaller one wherein we simply state, as an addendum to the current text, that identifiers are unique.

**Comment by chris-wood** [comment]
> @chris-wood in your first comment, you said that you only want to make the roles unique (i.e. a client cannot also be a server with the same PSK). This is not the same as what you say in your second comment: you want to make the identifiers unique. 

Ah, forgive me for sloppy notation. I'm referring to the identity of the peer, which, in the current text, is referred to as their role. 

To be clear, here's what I'm suggesting:

```
Applications which require authenticating finer-grained roles while still configuring a single shared PSK across all nodes can resolve this mismatch either by exchanging roles over the TLS connection after the handshake or by incorporating the unique roles (or identities) of both the client and server into the IPSK context string. 
```

It seems this captures precisely what you're after. Do you disagree? If not, what's missing? 

I think anything more is an application decision that's out of scope for this draft since, IMO, the Selfie "attack" is truly a misconfiguration issue. 

> And it is worth considering if this draft should update 8446.

I do not think an update to 8446 is needed.

**Comment by chris-wood** [comment]
@martinthomson, what do you think here?

**Comment by chris-wood** [comment]
Rejecting this PR based on discussion in Singapore.

**Pull request closed without merging**
